[package]
name = "enumset_derive"
version = "0.5.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

description = "An internal helper crate for enumset. Not public API."

documentation = "https://lymia.moe/doc/enumset/enumset/"
repository = "https://github.com/Lymia/enumset"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "Lymia/enumset", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[features]
serde = []

[dependencies]
darling = "0.10.0"
syn = "1"
quote = "1"
proc-macro2 = "1"
