language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.31.0 # minimum version supported by enumset
    - rust: 1.36.0 # minimum version trybuild supports

    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/enumset"
        - cargo test
        - cargo test --features serde
        - cargo test --features nightly
        - cargo test --features serde,nightly


script:
  - cd "${TRAVIS_BUILD_DIR}/enumset"
  - cargo test
  - cargo test --features serde
