language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # TODO: This is temporarily disabled until I have time to investigate what's up with byteorder in 1.31.0
    #- rust: 1.31.0

script:
  - cd "${TRAVIS_BUILD_DIR}/enumset"
  - cargo test
  - cargo test --features serde
  - cargo test --release
  - cargo test --features serde --release
